### ISSUE TITLE
对不起，浏览器sessionId失效，请重新获取

### ISSUE THREAD

**Issue by inexttomorrow** [rubyangxg/jd-qinglong#11]
![image](https://user-images.githubusercontent.com/14350370/133816643-eb6e93d7-0eed-4c43-98b5-7f0c99cf68e1.png)

**Comment by tingyue-wu** [comment]
昨天的版本到今早就是不断提示这个sessionId失效，请重新获取
，换了今天fix bug的镜像，不提示了，但是下方显示“无青龙配置”

**Comment by rubyangxg** [comment]
操作时限默认是3分钟，到期会强制剔除下线，为了避免长时间占用chrome资源
