### ISSUE TITLE
怎么映射文件夹，有时更新了一两个文件也要重新拉取镜像太费事

### ISSUE THREAD

**Issue by tingyue-wu** [rubyangxg/jd-qinglong#12]
怎么映射文件夹，有时更新了一两个文件也要重新拉取镜像太费事。
如果文件夹映射好了，只要下载更新的文件替换就好了，不需要重新拉取镜像

**Comment by rubyangxg** [comment]
我会优化的，因为好多想图省事儿，为了避免很多小白问问题，所以我就做了个大的allinone镜像。没有做前后端分离，之后可以自定义一下页面什么的
