### ISSUE TITLE
我有一个大胆的想法

### ISSUE THREAD

**Issue by q15118741477** [rubyangxg/jd-qinglong#17]
我有两个服务器，一个是暂时是空壳的只装了一个阿东短信ck，另一个是日常跑脚本的，可以不可以吧阿东短信换取的ck自动添加到跑脚本的服务器上，这样就可以不用因为服务器占用太多资源然后崩掉，大佬这个能实现吗

**Comment by yatokk** [comment]
你在空壳服务器随便搭了个空壳青龙,然后阿东的env.properties里面板路径填你跑脚本的路径,我在本地虚拟机试过了
