### ISSUE TITLE
webapp运行失败，不知道在哪添加ck，求告知，谢谢

### ISSUE THREAD

**Issue by koyangyang** [rubyangxg/jd-qinglong#2]
2021-09-16 01:41:31.886  INFO 1 --- [           main] com.meread.selenium.WebDriverFactory     : 初始化青龙面板aa登录失败, 获取到的ck无法上传，已忽略
�2021-09-16 01:41:32.011 ERROR 1 --- [           main] com.meread.selenium.WebDriverFactory     : cc获取token失败，请检查配置
�2021-09-16 01:41:32.012  WARN 1 --- [           main] com.meread.selenium.WebDriverFactory     : cc获取token失败，获取到的ck无法上传，已忽略
�2021-09-16 01:41:32.019 ERROR 1 --- [           main] com.meread.selenium.WebDriverFactory     : ee获取token失败，请检查配置
�2021-09-16 01:41:32.019  WARN 1 --- [           main] com.meread.selenium.WebDriverFactory     : ee获取token失败，获取到的ck无法上传，已忽略
�2021-09-16 01:41:32.020  WARN 1 --- [           main] com.meread.selenium.WebDriverFactory     : 请配置至少一个青龙面板地址! 否则获取到的ck无法上传

**Comment by rubyangxg** [comment]
不配置青龙也可以运行成功，主要问题不在这  你看看最后的日志有启动成功几个字吗

**Comment by koyangyang** [comment]
[#](https://github.com/rubyangxg/jd-qinglong/issues/5)和这个问题一样
