### ISSUE TITLE
考虑一下模拟扫码登录把铁子

### ISSUE THREAD

**Issue by 764763903a** [rubyangxg/jd-qinglong#3]
https://passport.jd.com/new/login.aspx?ReturnUrl=https%3A%2F%2Fwww.jd.com%2F
模拟这个页面的扫码登录 
另对接一下XDD-PLUS我开接口给你对接嘿嘿

**Comment by rubyangxg** [comment]
扫这个以后，貌似不能获取到想要的ck

**Comment by 764763903a** [comment]
> 扫这个以后，貌似不能获取到想要的ck

有没有CK格式 可以发TG给我 我做模糊匹配 不管多长只要里面带有pin和key就能成

**Comment by jy0703** [comment]
没用的，不是m,jd.com的扫码都没用，有些活动的做不了任务
