### ISSUE TITLE
出现破解滑块时会崩溃 具体报错如下

### ISSUE THREAD

**Issue by xsj684135** [rubyangxg/jd-qinglong#4]
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00000000000021c6, pid=1, tid=0x00007f782c15eb10
#
# JRE version: OpenJDK Runtime Environment (8.0_212-b04) (build 1.8.0_212-b04)
# Java VM: OpenJDK 64-Bit Server VM (25.212-b04 mixed mode linux-amd64 compressed oops)
# Derivative: IcedTea 3.12.0
# Distribution: Custom build (Sat May  4 17:33:35 UTC 2019)
# Problematic frame:
# C  0x00000000000021c6
#
# Core dump written. Default location: //core or core.1
#
# An error report file with more information is saved as:
# //hs_err_pid1.log
#
# If you would like to submit a bug report, please include
# instructions on how to reproduce the bug and visit:
#   https://icedtea.classpath.org/bugzilla

**Comment by rubyangxg** [comment]
此问题已修复，升级了jdk到11，麻烦拉最新镜像

**Comment by xsj684135** [comment]
谢谢大佬 大佬牛逼
