### ISSUE TITLE
jd-qinglong-群晖安装教程

### ISSUE THREAD

**Issue by ljhnchina** [rubyangxg/jd-qinglong#9]
感谢群规 @yang jungle 提供教程
[jd-qinglong-群晖安装教程.pdf](https://github.com/rubyangxg/jd-qinglong/files/7185951/jd-qinglong-.pdf)

**Comment by rui3bo2** [comment]
额 第一部的文件哪里来的？小白求指教

**Comment by ljhnchina** [comment]
> 额第一部的文件哪里来的？小白求指教

https://github.com/rubyangxg/jd-qinglong/blob/master/env.template.properties
下载后修改保存并更改名字为env.properties就可以了

**Comment by rui3bo2** [comment]
多谢大佬指教

**Comment by rui3bo2** [comment]
没有足够的资源调度，请稍后重试?

**Comment by ljhnchina** [comment]
> 没有足够的资源调度，请稍后重试？

内测不够
